/**
 * Single source of truth for brand, contact and SEO defaults.
 *
 * Anything that appears in more than one place (phone number, e-mail, social
 * profiles, brand colours) lives here. Components read from this file instead
 * of hardcoding literals.
 */

const WHATSAPP_NUMBER = process.env.REACT_APP_WHATSAPP_NUMBER || "917013160560";

const siteConfig = {
  name: "Sri Simbha Ad Solutions",
  shortName: "Sri Simbha Ad Solutions",
  legalName: "SriSimbhaAdSolutions",
  tagline: "We Don’t Just Show Ads. We Command Attention.",
  url: (process.env.REACT_APP_SITE_URL || "https://simbha.vercel.app").replace(
    /\/$/,
    ""
  ),
  locale: "en_IN",

  description:
    "Sri Simbha Ad Solutions is a Visakhapatnam based advertising agency offering LED display ads, tea cup printing, digital marketing, website building, ads on wheels and ad film production.",

  logoAlt: "Sri Simbha Ad Solutions logo",

  themeColor: "#facc15",

  /**
   * 1200x630 social share card, generated by `scripts/optimize-images.js`.
   * Open Graph and Twitter both reject anything under 200x200 in practice, so
   * the 180x180 touch icon is no longer reused as a fallback.
   */
  shareImage: "/og-image.png",

  /**
   * Machine-readable business facts. These feed the `LocalBusiness` JSON-LD
   * that `utils/structuredData.js` emits, which is what lets Google show the
   * knowledge panel, opening hours and map pin for a local advertiser.
   */
  business: {
    type: "AdvertisingAgency",
    priceRange: "₹₹",
    foundingYear: "2019",
    /**
     * Coordinates for Gajuwaka, Visakhapatnam. Used for the `geo` property;
     * drop them if the office moves so the schema never points at the wrong pin.
     */
    geo: { latitude: 17.7758, longitude: 83.35 },
    openingHours: [
      {
        days: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
        opens: "09:00",
        closes: "20:00",
      },
    ],
    /** Neighbourhoods and nearby towns the team actively sells into. */
    areaServed: [
      "Visakhapatnam",
      "Gajuwaka",
      "MVP Colony",
      "Dwaraka Nagar",
      "Port Road",
      "Bheemilipalem",
      "Anakapalle",
      "Vizianagaram",
      "Rajahmundry",
    ],
    paymentAccepted: ["Cash", "UPI", "Bank Transfer"],
    currenciesAccepted: "INR",
  },

  contact: {
    email: "srisimbhaadsolutions.info@gmail.com",
    emailSubject: "Enquiry for Sri Simbha Ad Solutions",
    phone: "+91 70131 60560",
    phoneDigits: "917013160560",
    whatsappNumber: WHATSAPP_NUMBER,
    whatsappMessage:
      "Hi Sri Simbha Team, I'm interested in your advertising services!",
    address: "Gajuwaka, Visakhapatnam, Andhra Pradesh",
    mapsUrl:
      "https://www.google.com/maps/place/Gajuwaka,+Visakhapatnam,+Andhra+Pradesh",
  },

  social: [
    {
      id: "facebook",
      label: "Facebook",
      href: "https://www.facebook.com/Simbhaadagency",
    },
    {
      id: "instagram",
      label: "Instagram",
      href: "https://www.instagram.com/simbhaadagency",
    },
    {
      id: "linkedin",
      label: "LinkedIn",
      href: "https://www.linkedin.com/company/simbha-ad-agency",
    },
    {
      id: "youtube",
      label: "YouTube",
      href: "https://www.youtube.com/@Simbha-ads",
    },
    {
      id: "twitter",
      label: "X (Twitter)",
      href: "https://twitter.com/simbhaadagency",
    },
  ],
};

export const buildWhatsAppUrl = (
  message = siteConfig.contact.whatsappMessage
) =>
  `https://wa.me/${siteConfig.contact.whatsappNumber}?text=${encodeURIComponent(
    message
  )}`;

export const buildMailTo = (subject = siteConfig.contact.emailSubject) =>
  `mailto:${siteConfig.contact.email}?subject=${encodeURIComponent(subject)}`;

export const buildTelUrl = () => `tel:+${siteConfig.contact.phoneDigits}`;

export default siteConfig;
